default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt
      password: dbtcourse
      port: 5432
      dbname: dbt_project
      schema: jaffle_shop
      threads: 1